steps:
- id: 'build image'
  name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/${PROJECT_ID}/myreact-app:$SHORT_SHA'
    - '.'
    - '-f'
    - './Dockerfile'
  timeout: 2000s
- id: 'push to container registry'
  name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'push'
    - 'gcr.io/my-project-1521209271666/myreact-app:$SHORT_SHA'
- id: 'deploy to gke'
  name: 'gcr.io/cloud-builders/gcloud'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-central2-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
    - 'KUBECONFIG=/.kube/config'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
          
          gcloud container clusters get-credentials my-cluster --project my-project-1521209271666 --zone europe-central2-a
          sed -i 's|gcr.io/project-id/myreact-app|gcr.io/my-project-1521209271666/myreact-app:$SHORT_SHA|' ./deployment.yaml
          kubectl apply -f ./deployment.yaml
timeout: 2000s

# 'auth', 'activate-service-account', '1060866810332-compute@developer.gserviceaccount.com', '--key-file=my-project-1521209271666-d48bd4f231cf.json', '--project=my-project-1521209271666'